name: org_auth_ui_dev
description: Authentication UI widgets (login/signup/2FA) for organizations.
version: 0.0.1
homepage: https://mit.com/org_auth_ui_dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.1.2
  provider: ^6.0.1
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.1
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true

flutter_gen_l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: org_auth_localizations.dart
    output-class: OrgAuthLocalizations
    synthetic-package: false